server:
  port: 8801
  tomcat:
    max-connections: 20480
    accept-count: 20480
    keep-alive-timeout: -1
    connection-timeout: 65000

spring:
  application:
    name: ua-benchmark
  # Virtual Threads
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always

# Yauaa 캐시 설정 (yauaa-cache 프로파일 전용)
ua:
  yauaa:
    cache-size: 10000   # 최근 N개 UA 결과 캐싱, 필요에 따라 조정


logging:
  level:
    com.benchmark.ua: DEBUG
    root: INFO
